In [79]:
import numpy as np
import matplotlib.pyplot as plt
from numpy.linalg import inv

In [80]:
train = np.arange(0, 2*np.pi, 0.1)
test = np.arange(0.05, 2*np.pi, 0.1)

#print(train)
#print(test)

In [81]:
ntrain = np.random.normal(0, 0.1, len(train))
ntest = np.random.normal(0, 0.1, len(test))
train += ntrain
test += ntest
#print(train)
#print(test)
w = np.random.rand(len(train))

In [82]:
def sinx(data):
    temp=[]
    for i in range(len(data)):
        temp.append(np.sin(2*data[i]))
    return np.array(temp)
#y=sinx(train)
#y

In [83]:
def sinx_square(data):
    temp=[]
    for i in range(len(data)):
        temp.append(np.sign(np.sin(2*data[i])))
    return np.array(temp)
#y=sinx_square(train)
#y

In [84]:
def phi(x, mu, sigma):
    phi = np.exp(-(x-mu)**2/(2*sigma**2))
    return phi

In [85]:
def phi_matrix(x, mu, sigma):
    mat = np.zeros((len(x), len(mu)))
    for i in range(len(x)):
        for j in range(len(mu)):
            mat[i][j] = phi(x[i], mu[j], sigma[j])
    return mat

In [86]:
def f_function(x, mu, sigma, weights):
    y = np.zeros(len(x))
    for i in range(len(x)):
        add = 0
        for j in range(len(mu)):
            add += phi(x[i], mu[j], sigma[j])*weights[j]
        y[i] = add
    return y

In [87]:
def batch_learning(phi, f):
    temp = inv(np.matmul(np.transpose(phi), phi))
    w = np.matmul(np.matmul(temp, np.transpose(phi)), np.transpose(f))
    return w

In [88]:
def error(y, f):
    sum = 0
    for i in range(len(y)):
        sum += np.absolute((y[i] - f[i]))**2
    return sum/len(y)

In [89]:
# didnt understand this part---need more reading
def chunkify(seq, num):
    #Divide the train set in "number of nodes" equal parts. 
    out = []

    if len(seq) % num == 0:
        length = len(seq) / num
        plus = 0
    else:
        length = len(seq) / num
        plus = len(seq) % num

    howmany = 0
    while howmany < len(seq):
        first = howmany
        last = first + length
        if plus > 0:
            last += 1
            plus -= 1
        out.append(seq[int(first):int(last)])
        howmany += (last - first)
    return out

def init_mus(nodes_number, train):
    mus = np.zeros(nodes_number)

    chunks = chunkify(train, nodes_number)
    for i,elem in enumerate(chunks):
        mean = np.mean(elem)
        mus[i] = mean
    return mus


In [91]:
nodes = np.arange(2,80, 10)
sigma1= 0.5
error_sinx_train = []
error_square_train = []
error_sinx_test = []
error_square_test = []
y_pred_sinx=[]
y_pred_sqaure=[]
y_pred_square_test=[]
y_pred_sinx_test=[]
w_sinx=[]
w_square=[]
iters=10
#nodes
y_sinx=sinx(train)
#y_sinx
y_square=sinx_square(train)
#ysquare
y_sinx_test=sinx(test)
#y_sinx_test
y_square_test=sinx_square(test)
#y_square_test
for i in range(1,iters):
    
    mu = init_mus(i, train)
    print(mu)
    sigma = np.ones(len(mu)) * sigma1
    phi1 = phi_matrix(train, mu, sigma)
    w_sinx = batch_learning(phi1, y_sinx)
    y_pred_sinx = f_function(train, mu, sigma, w_sinx)
    error_sinx_train.append(error(y_pred_sinx, y_sinx))
    
    w_square = batch_learning(phi1, y_square)
    y_pred_sqaure = f_function(train, mu, sigma, w_square)
    error_square_train.append(error(y_pred_sqaure, y_square))
    
    y_pred_sinx_test = f_function(test, mu, sigma, w_sinx)
    error_sinx_test.append(error(y_pred_sinx_test, y_sinx_test))
    
    y_pred_square_test = f_function(test, mu, sigma, w_square)
    error_square_test.append(error(y_pred_square_test, y_square_test))
    '''
    y_train = phi_matrix(train, mu, sigma)
    y_test = phi_matrix(test, mu, sigma)
    #print(y_train)
    #print(y_test)
    w_sinx = np.linalg.lstsq(y_train, y_sinx)
    #print(w_sinx)
    w_square = np.linalg.lstsq(y_train, y_square)
    #print(w_square)
    y_pred_sinx = np.dot(y_test,w_sinx[0])
    y_pred_square = np.dot(y_test,w_square[0])
    error_sinx.append(error(y_pred_sinx, y_sinx_test))
    error_square.append(error(y_pred_square, y_square_test))
print(error_sinx)
print(error_square)
'''
print(error_sinx_train)
print(error_square_train)
print(error_sinx_test)
print(error_square_test)

[3.09033101]
[1.53259356 4.69831805]
[0.9755734  3.10103599 5.19438364]
[0.72278923 2.3875211  4.10818699 5.59224526]
[0.56794569 1.93040319 3.31852602 4.58964369 5.74757089]
[0.47292299 1.62535236 2.80301685 3.90678767 4.94077116 5.8461139 ]
[0.37558752 1.28062703 2.16700085 3.11000017 4.01281009 4.89257009
 5.79372133]
[0.32172229 1.17818898 2.08824406 3.00353057 3.90741684 4.78277138
 5.69916861 6.18319135]
[0.27028489 0.98397657 1.67245875 2.39007767 3.11226652 3.8007638
 4.49266861 5.20094321 5.8895391 ]
[0.4882639963404581, 0.48819708013599705, 0.33260044490649676, 0.02144530861933926, 0.16371740254480605, 0.061622238589626316, 0.011487891033503925, 0.004309659193266001, 0.0019412577650029337]
[0.9971573394482843, 0.9974839695944131, 0.7420613115979888, 0.17371236043466085, 0.36889606444611345, 0.21317400361837396, 0.14445330761589173, 0.1441490072236326, 0.13600128328564742]
[0.49223702515308365, 0.4936632083966312, 0.3249358070838759, 0.02446329128207373, 0.1726376718425306, 0.